services:
  - type: web
    name: grand-mebel-invoices
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: grand-mebel-invoices-db
          property: connectionString

databases:
  - name: grand-mebel-invoices-db
    plan: free
